services:
  dashboard:
    container_name: dashboard
    image: public.ecr.aws/s2m1f3k2/ggezlabs/hummingbot-dashboard:2.7.0
    build:
      context: .. # Use the parent directory (hummingbot_setup_2.7) as the build context
      dockerfile: hummingbot-dashboard/Dockerfile # Specify the path to the Dockerfile relative to the context
    ports:
      - "8501:8501"
    environment:
      - AUTH_SYSTEM_ENABLED=False
      - BACKEND_API_HOST=hummingbot-api
      - BACKEND_API_PORT=8000
      - BACKEND_API_USERNAME=admin
      - BACKEND_API_PASSWORD=admin
      - HASURA_GRAPHQL_URL=http://localhost:8443/v1/graphql
    volumes:
      - .:/home/dashboard
    networks:
      - shared-network
networks:
  shared-network:
    external: true
