name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - sqlalchemy
  - pip
  - pandas>=2.0.3
  - aiohttp>=3.8.5
  - pydantic>=2
  - pip:
      - nest_asyncio
      - pydantic
      - streamlit>=1.36.0
      - watchdog
      - python-dotenv
      - plotly==5.24.1
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pyyaml
      - pathlib
      - streamlit-authenticator==0.3.2
      - flake8
      - isort
      - pre-commit
