name: Dashboard Docker CI Pipeline

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
      - DEV-Branch
    paths: ['!terraform/**']

jobs:
  build:
    name: Build, Scan, and Deploy Docker Image
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      REPO_NAME: ggez                        # REPOSITORY: ${{ env.REPO_NAME }}
      ECS_SERVICE: ggez-service-prod             # set this to your Amazon ECS service name
      ECS_CLUSTER: ggez-ecs-cluster-prod         # set this to your Amazon ECS cluster name
      ECS_TASK_DEFINITION: ./task-definition/ggez-prod.json
      CONTAINER_NAME: ggez-hummingbot-dashboard-prod                  # set this to the name of the container in the task definition

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:${{ github.sha }} .
          
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # - name: Trivy Scan Docker Image
      #   id: trivy-scan
      #   run: |
      #     docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
      #     docker run --rm aquasec/trivy:latest image $REGISTRY/$REPOSITORY:$IMAGE_TAG
      #   env:
      #     DOCKER_IMAGE: ${{ steps.build-image.outputs.image }}

      # - name: Render Amazon ECS task definition
      #   id: task-def
      #   env:
      #     AWS_REGION: ${{ env.AWS_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: ${{ env.REPO_NAME }}
      #     IMAGE_TAG: latest
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition: ${{ env.ECS_TASK_DEFINITION }}
      #     container-name: ${{ env.CONTAINER_NAME }}
      #     image: ${{ steps.build-image.outputs.image }}

      # - name: Deploy to Amazon ECS service
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     service: ${{ env.ECS_SERVICE }}
      #     cluster: ${{ env.ECS_CLUSTER }}
